baseURL: "https://example.org"
languageCode: "en-us"
title: "Ling Zhai"
theme: hugo-profile

Paginate: 3
disqusShortname: lignzhai
googleAnalytics: G-lignzhai

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    # #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 2
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Ling Zhai"
  description: My Portfolio
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ling Zhai."
    subtitle: "I build the Mobile Apps and Web Front-End"
    content: "Just give me your ideas, and I will turn your ideas into reality.
Please present any unresolved problems to me, and I will solve your problems.

As a software developer for over 10 years, I have experience working in various fields of website and mobile development. While passing the bachelor's and master's programs, I acquired the basic knowledge of computer programming.
After graduating from university, I joined various companies and was involved in various projects, gaining rich experience.
In the process, I worked individually and as a team member, and in some projects, I gained a lot of experience, such as working as a lead.
In the process, no new language was a problem for me, and in a short time, I became familiar with the language.

Let's do anything together.
"
    image: /images/hero.svg
    button:
      enable: true
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: "https://github.com/lingzhai6"
        - icon: fab fa-linkedin
          url: "https://www.linkedin.com/in/ling-zhai-88013a226/"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: "
      Just give me your ideas, and I will turn your ideas into reality.
Please present any unresolved problems to me, and I will solve your problems.

As a software developer for over 10 years, I have experience working in various fields of website and mobile development. While passing the bachelor's and master's programs, I acquired the basic knowledge of computer programming.
After graduating from university, I joined various companies and was involved in various projects, gaining rich experience.
In the process, I worked individually and as a team member, and in some projects, I gained a lot of experience, such as working as a lead.
In the process, no new language was a problem for me, and in a short time, I became familiar with the language.

Let's do anything together.
"
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "JavaScript"
        - "TypeScript"
        - "React Native"
        - "React"
        - "Node"
        - "Express"
        - "Dart"
        - "Swift"
        - "Kotlin"
        - "MongoDB"
        - "AWS"
        - "HTML"
        - "CSS"
        - "SQLite"

  # Experience
  experience:
    enable: true
    items:
      - job: "React | React Native Developer"
        company: "Cubix"
        companyUrl: "https://cubix.com"
        date: "February 2014 - March 2017"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://cubix.com"
        content: "I worked as a React | React Native Developer at [Cubix LLC.](https://cubix.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "Software Engineer"
        company: "Pointters"
        companyUrl: "https://pointters.com"
        date: "May 2016 - December 2018"
        featuredLink:
          enable: true
          url: "https://pointters.com"
        info:
          enable: true
          content: I worked as a software endgineer for more than one year in Amazon.
        content: |
          I worked as a software endgineer at [Pointters LLC.](https://pointters.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead Front End developer for a product.
          - Created a frontend design for a product.

      - job: "Senior Software Engineer"
        company: "Blackish Tech"
        companyUrl: "https://blackishtech.com"
        date: "January 2019 - Present"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "https://blackishtech.com"
        content: |
          I am currently working as a software developer at [Blackish Tech.](https://blackishtech.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead React Native developer for a product.
          - Created a frontend design for a product.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Information Technology (MIT), Computer engineering"
        school:
          name: "Carnegie Mellon University"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science (BS), Computer engineering"
        school:
          name: "Carnegie Mellon University"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://google.com
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://google.com

  # projects
  projects:
    enable: true
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
    email: lingzhai6@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/lingzhai6
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com
